version: '3.9'

services:
  api:
    environment:
      - Database:DataSource=db
    build:
      context: ./api/src
      dockerfile: OpenBookLibrary.Api/Dockerfile
    ports:
      - 80
      - 433
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - '1433:1433'
